#!/bin/bash
# Filmbot Google Drive Sync Script
# This file is auto-generated by the Filmbot UI
# Manual edits will be overwritten when Drive settings change

RECORDINGS_DIR="/mnt/nvme/recordings"
DRIVE_DEST="filmbot-drive:Recordings"
LOG_FILE="/var/log/filmbot-rclone.log"

# Ensure log file exists
touch "$LOG_FILE"

# Sync recordings to Google Drive
echo "$(date): Starting sync to $DRIVE_DEST" >> "$LOG_FILE"

rclone move "$RECORDINGS_DIR" "$DRIVE_DEST" \
    --log-file="$LOG_FILE" \
    --log-level INFO \
    --transfers 1 \
    --checkers 1 \
    --stats 30s \
    --stats-one-line \
    --delete-empty-src-dirs

if [ $? -eq 0 ]; then
    echo "$(date): Sync completed successfully" >> "$LOG_FILE"
else
    echo "$(date): Sync failed with error code $?" >> "$LOG_FILE"
fi

