#!/usr/bin/env python3
"""
Helper script to update sync-drive.sh with the configured Google Drive path.
This should be called when the Drive configuration changes in the UI.
"""

import sys
from pathlib import Path
from config_manager import ConfigManager


SYNC_SCRIPT_PATH = Path("/opt/filmbot-appliance/sync-drive.sh")
SYNC_SCRIPT_TEMPLATE = """#!/bin/bash
# Filmbot Google Drive Sync Script
# Auto-generated by Filmbot UI

RECORDINGS_DIR="/mnt/nvme/recordings"
DRIVE_DEST="{drive_destination}"
LOG_FILE="/var/log/filmbot-rclone.log"

# Ensure log file exists
touch "$LOG_FILE"

# Sync recordings to Google Drive
echo "$(date): Starting sync to $DRIVE_DEST" >> "$LOG_FILE"

rclone move "$RECORDINGS_DIR" "$DRIVE_DEST" \\
    --log-file="$LOG_FILE" \\
    --log-level INFO \\
    --transfers 1 \\
    --checkers 1 \\
    --stats 30s \\
    --stats-one-line

if [ $? -eq 0 ]; then
    echo "$(date): Sync completed successfully" >> "$LOG_FILE"
else
    echo "$(date): Sync failed with error code $?" >> "$LOG_FILE"
fi
"""


def update_sync_script(config: ConfigManager) -> bool:
    """Update the sync-drive.sh script with current Drive configuration.
    
    Args:
        config: Configuration manager instance
        
    Returns:
        True if successful, False otherwise
    """
    drive_config = config.get_drive_config()
    remote = drive_config['remote']
    folder = drive_config['folder']
    
    # Build full destination path
    drive_destination = f"{remote}{folder}"
    
    # Generate script content
    script_content = SYNC_SCRIPT_TEMPLATE.format(drive_destination=drive_destination)
    
    try:
        # Write script
        with open(SYNC_SCRIPT_PATH, 'w') as f:
            f.write(script_content)
        
        # Make executable
        SYNC_SCRIPT_PATH.chmod(0o755)
        
        print(f"✓ Updated {SYNC_SCRIPT_PATH}")
        print(f"  Destination: {drive_destination}")
        return True
        
    except PermissionError:
        print(f"✗ Permission denied writing to {SYNC_SCRIPT_PATH}")
        print("  Run with sudo or ensure user has write access")
        return False
        
    except Exception as e:
        print(f"✗ Error updating sync script: {e}")
        return False


def main():
    """Main entry point."""
    config = ConfigManager()
    
    if not config.is_initialized():
        print("Error: Filmbot not initialized. Run setup wizard first.")
        sys.exit(1)
    
    drive_config = config.get_drive_config()
    
    if not drive_config['remote'] or not drive_config['folder']:
        print("Error: Google Drive not configured")
        sys.exit(1)
    
    print("Updating sync-drive.sh with current configuration...")
    print(f"  Remote: {drive_config['remote']}")
    print(f"  Folder: {drive_config['folder']}")
    print()
    
    if update_sync_script(config):
        print("\nSync script updated successfully!")
        print("The filmbot-sync.timer will use this configuration on next run.")
        sys.exit(0)
    else:
        print("\nFailed to update sync script")
        sys.exit(1)


if __name__ == "__main__":
    main()

